export const siteSettings = {
  businessName: 'Swift7',
  tagline: 'Your business website, live in 7 days.',
  phone: '07380 218301',
  email: 'hello@swift7.co.uk',
  address: 'Hull, East Yorkshire, United Kingdom',
  openingHours: 'Monday to Friday, 9am to 5pm',
  primaryCtaLabel: 'Claim my slot',
  primaryCtaLink: '#start',
  footerText: 'Your business website, live in 7 days.',
  copyrightText: '© 2026 Swift7. All rights reserved.',
  socialLinks: [{ platform: 'WhatsApp', url: 'https://wa.me/447380218301' }],
  seo: {
    title: 'Swift7 | Affordable Web Design | Live in 7 Days',
    description: 'Professional websites for UK small businesses. £500 all-in, live in 7 days. Mobile-friendly, built to rank on Google. Content written for you.',
    ogTitle: 'Swift7 — Affordable Web Design, Live in 7 Days | £500 All-In',
    ogDescription: 'Professional websites for UK small businesses. £500 all-in, live in 7 days. Mobile-friendly, built to rank on Google. Content written for you.',
  },
};

export const navigation = {
  headerLinks: [
    { label: 'Portfolio', href: '/portfolio' },
    { label: "What's Included", href: '/whats-included' },
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Swift7 Plus', href: '/swift7-plus' },
  ],
  footerLinks: [
    { label: "What's Included", href: '/whats-included' },
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Our Work', href: '/portfolio' },
    { label: 'About', href: '/about' },
    { label: 'Swift7 Plus', href: '/swift7-plus' },
  ],
  ctaLink: { label: 'Claim my slot', href: '#start' },
  socialLinks: [{ platform: 'WhatsApp', url: 'https://wa.me/447380218301' }],
};

export const services = [
  {
    name: 'Swift7 Launch',
    slug: 'swift7-launch',
    shortDescription: '£500 all-in website for trades, local businesses and startups needing a credible site fast.',
    ctaLabel: 'Claim my slot',
    ctaLink: '#start',
    displayOrder: 1,
    featured: true,
    price: '£500',
    timeline: 'Live in 7 days',
    features: ['All content written for you', 'Up to 10 pages, mobile-first', 'Basic SEO setup + 5 articles', 'Google Business Profile setup', 'Domain, hosting, SSL + emails', 'Analytics + lead capture forms'],
    seo: {
      title: 'Swift7 Launch | £500 Website Live in 7 Days',
      description: 'The Swift7 Launch is a £500 all-in website package for UK small businesses, live in 7 days with copy, SEO, hosting and Google Business Profile setup.',
    },
  },
  {
    name: 'Swift7 Trust',
    slug: 'swift7-trust',
    shortDescription: 'Trust-focused premium design for accountants, solicitors, clinics and consultants.',
    ctaLabel: 'Claim my slot',
    ctaLink: '#start',
    displayOrder: 2,
    featured: true,
    price: '£995',
    timeline: 'Live in 10 days',
    features: ['Everything in Launch', 'Trust-focused premium design', 'Credentials, reviews & proof sections', 'Professional services page structure', 'Conversion-optimised copy', 'Enhanced SEO + 8 articles'],
    seo: {
      title: 'Swift7 Trust | Trust-Focused Website Package',
      description: 'Swift7 Trust is a premium trust-focused website package for professional services businesses that need credibility and enquiries.',
    },
  },
  {
    name: 'Swift7 Plus',
    slug: 'swift7-plus',
    shortDescription: 'Advanced SEO, booking features, branding and conversion support for growth-focused businesses.',
    ctaLabel: 'Find out more',
    ctaLink: '/swift7-plus',
    displayOrder: 3,
    featured: false,
    price: '£1,495+',
    timeline: 'Live in 10–14 days',
    features: ['Everything in Trust', 'Advanced SEO foundations', 'Booking & advanced lead features', '10 SEO articles', 'Brand & visual direction', 'Conversion optimisation'],
    seo: {
      title: 'Swift7 Plus | Advanced Website and SEO Package',
      description: 'Swift7 Plus is for businesses that need advanced SEO, booking features, brand direction and conversion-focused website design.',
    },
  },
];

export const caseStudies = [
  {
    clientName: 'JT Accountancy',
    slug: 'jt-accountancy',
    industry: 'Accountancy',
    location: 'Hull',
    summary: 'Professional site for a Hull accountancy practice — built to attract limited companies, sole traders and personal tax clients across Hull and East Yorkshire.',
    challenge: 'JT Accountancy needed a professional online presence that made the firm feel credible and easy to contact.',
    solution: 'Swift7 created a fast static site with local SEO foundations, clear service messaging and conversion-focused calls to action.',
    results: 'The business now has a polished site that explains the offer clearly and supports local search visibility.',
    featuredImage: '/work-jt-accountancy.webp',
    displayOrder: 1,
    featured: true,
    seo: { title: 'JT Accountancy Case Study | Swift7', description: 'A professional Swift7 website for a Hull accountancy practice.' },
  },
  {
    clientName: 'Hull Cleaning',
    slug: 'hull-cleaning',
    industry: 'Cleaning',
    location: 'Hull',
    summary: 'Mobile-friendly site for a local cleaning business — with service pages, enquiry forms, and Google Business Profile to drive local leads.',
    challenge: 'Hull Cleaning needed a proper website that could turn local searches into enquiries.',
    solution: 'Swift7 built a mobile-first static website with service pages, lead capture and Google Business Profile support.',
    results: 'The site gives customers a clear route from search to enquiry and makes the business look more established.',
    featuredImage: '/work-hull-cleaning.webp',
    displayOrder: 2,
    featured: true,
    seo: { title: 'Hull Cleaning Case Study | Swift7', description: 'A mobile-first website for a local cleaning company in Hull.' },
  },
  {
    clientName: 'Elland Road Roofing',
    slug: 'elland-road-roofing',
    industry: 'Roofing',
    location: 'Yorkshire',
    summary: 'WordPress site for a Yorkshire roofer — ranking on Google for local search terms and generating quote requests directly through the site.',
    challenge: 'The business needed a roofing website that could show services, proof and contact options clearly.',
    solution: 'Swift7 created a WordPress site with strong service sections, local SEO structure and easy content management.',
    results: 'The site supports local ranking and direct quote requests.',
    featuredImage: '/elland-road-2.webp',
    displayOrder: 3,
    featured: true,
    seo: { title: 'Elland Road Roofing Case Study | Swift7', description: 'A WordPress roofing website built by Swift7.' },
  },
  {
    clientName: 'UseForge',
    slug: 'useforge',
    industry: 'App landing page',
    location: 'UK',
    summary: 'Fast, clean app landing page built for conversions — driving app store downloads with a clear mobile-first layout.',
    challenge: 'UseForge needed a simple landing page that explained the product and pushed users toward download.',
    solution: 'Swift7 designed and built a fast static landing page with focused messaging and app-store conversion points.',
    results: 'A clearer product story and mobile-first route to download.',
    featuredImage: '/use-forge-3.webp',
    displayOrder: 4,
    featured: true,
    seo: { title: 'UseForge Case Study | Swift7', description: 'A fast app landing page designed and built by Swift7.' },
  },
  {
    clientName: 'Apex Strength',
    slug: 'apex-strength',
    industry: 'Fitness',
    location: 'Hull',
    summary: 'Concept site for a Hull-based gym — bold design built to drive memberships, with class timetables, pricing, and a strong mobile-first layout.',
    challenge: 'Apex needed a bold concept showing how a gym website could drive memberships.',
    solution: 'Swift7 created a strong visual direction with pricing, timetable and membership conversion sections.',
    results: 'A polished concept that shows how a fitness site can feel premium and sales-focused.',
    featuredImage: '/work-apex-gym.webp',
    displayOrder: 5,
    featured: true,
    seo: { title: 'Apex Strength Case Study | Swift7', description: 'A gym website concept created by Swift7.' },
  },
];

export const testimonials = [
  {
    clientName: 'Marie M.',
    company: 'Hull Cleaning Co.',
    reviewText: "Honestly didn't have to do much at all. Filled in a form, Callum wrote everything, and it was live within the week. Already had people contact us through it.",
    starRating: 5,
    source: 'Google',
    displayOrder: 1,
  },
  {
    clientName: 'Steve D.',
    company: 'Elland Road Roofing',
    reviewText: 'Thought the 7 days thing was a gimmick. Callum had it done in 6. Had a couple of people get in touch through the site not long after it went live.',
    starRating: 5,
    source: 'Google',
    displayOrder: 2,
  },
  {
    clientName: 'Isabelle B.',
    company: 'UseForge',
    reviewText: 'I just answered some questions about the business and that was pretty much it. Callum sorted the domain, emails, everything. Good value for what you get.',
    starRating: 5,
    source: 'Google',
    displayOrder: 3,
  },
];

export const faqs = [
  ['Can you really launch my website in 7 days?', 'Yes. Once we have your business details and the first payment, we start immediately and work to a tight 7-day launch process. Day 1 is your brief, days 2–5 we build, day 6 you review, day 7 you go live.'],
  ['What do I need to provide?', 'Just a short business brief, your logo if you have one, any existing images, and the best way for customers to contact you.'],
  ['Do I have to write the content myself?', 'No. We write the website copy for you, including page content, calls to action, SEO titles, descriptions, and starter articles.'],
  ['How many pages are included?', 'The Swift7 Launch includes up to 10 pages, usually covering home, about, services, service detail pages, blog/articles, and contact.'],
  ['Is hosting included?', 'Yes. Your first year of domain, hosting, and SSL is included. After that, renewal is £70 per year for domain and hosting.'],
  ['What if I need changes?', 'You review a preview before launch. We handle sensible revisions quickly so the site still goes live on schedule.'],
  ['How does payment work?', 'Payment is split 50% upfront and 50% on completion, so you only pay the final balance when the website is ready to launch.'],
  ['Will the website work on mobile?', 'Yes. Every site is designed mobile-first, then refined for tablets and desktops so it feels clean and fast everywhere.'],
  ['Do you set up Google Business Profile?', "Yes. We set up and optimise your Google Business Profile as part of the package. If you already have a profile, we'll optimise what's there."],
  ['What if I need something more bespoke?', 'If you need stronger SEO, premium design or advanced lead features, Swift7 Plus is built for that. For ecommerce or custom apps, get in touch and we will point you in the right direction.'],
].map(([question, answer], index) => ({ question, answer, category: 'General', displayOrder: index + 1 }));

export const homepage = {
  title: 'Home',
  slug: '',
  heroHeading: 'A website that wins you work.',
  heroText: 'Professional, mobile-first websites for UK trades and small businesses. £500 all-in, live in seven days — content, SEO and Google Business Profile done for you.',
  cta: {
    heading: 'Stop putting it off.',
    text: "You've been meaning to sort this for months. Let's get it done this week.",
    label: 'Claim my slot',
    href: '#start',
  },
  seo: siteSettings.seo,
};
